version: '3.1'

services:

  db:
    image: postgres:10.5
    restart: always
    command: postgres -c max_prepared_transactions=100
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: money-transfer-app
    ports:
      - '8080:8080'
    depends_on:
      - db  # Wait for the 'db' service to be ready before starting 'app'
