version: '3.1'

services:

  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  flyway:
    image: flyway/flyway:9.16-alpine
    environment:
      - FLYWAY_URL=db
      - FLYWAY_USER=$DB_USER
      - FLYWAY_PASSWORD=$DB_PASS
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: money-transfer-app
    ports:
      - '8080'
      - '5005'
    network_mode: "host"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_HOST: $DB_URL
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_PASS
      SPRING_REDIS_HOST: localhost
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 86400000


