version: '3.1'

services:

  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes:
      - ./sql/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: money-transfer-app
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - db  # Wait for the 'db' service to be ready before starting 'app'
